/** @type {import('tailwindcss').Config} */
export default {
    content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
    theme: {
        extend: {
            backgroundImage: {
                footer: "url('/footer-bg.jpg')",
            },
            borderRadius: {
                3: "3px",
                4: "4px",
                5: "5px",
            },
            borderWidth: {
                0.6: "0.6px",
            },
            colors: {
                "home-top": "#010182",
                "home-bottom": "#000839",
                "home-gray": "#aeaeae",
                "home-link": "#7979cc",
                "navbar-text": "#151515",
                "navbar-hover": "#7979CC",
                "about-text": "#555555",
                "services-sub": "#959595",
                "client-bg": "#f5f5f5",
                "contact-bg-icons": "#eaf6e9",
                "contact-text": "#484848",
                "contact-input": "#ced4da",
                "contact-input-text": "#212529",
                "contact-input-place": "#6c757d",
                "contact-input-focus": "#007aff",
                "contact-bg-button": "#f0f0f0",
                "footer-border": "#222222",
                "btnUp-hover": "#97d193",
                "team-social": "rgba(124, 197, 118, 0.8)",
                "team-icon": "rgba(255, 255, 255, 0.7)",
                "footer-shadow": "rgba(0, 0, 0, 0.85)",
            },
            transitionDuration: {
                175: "175ms",
                225: "225ms",
                450: "450ms",
                600: "600ms",
            },
            transitionProperty: {
                bottom: "bottom",
            },
            fontFamily: {
                montserrat: ["Montserrat", "sans-serif"],
                opensans: ["Open Sans", "sans-serif"],
                poppins: ["Poppins", "sans-serif"],
            },
            fontSize: {
                13: "13px",
                15: "15px",
                22: "22px",
                26: "26px",
                27: "27px",
                28: "28px",
                32: "32px",
            },
            height: {
                22: "90px",
                42: "42px",
                42.5: "42.5px",
                126: "126px",
                168: "168px",
                492: "492px",
                636: "636px",
            },
            lineHeight: {
                22.5: "22.5px",
                26: "26px",
                28.8: "28.8px",
            },
            margin: {
                lima: "5px",
                15: "15px",
                17: "17px",
                18: "18px",
                30: "30px",
                55: "55px",
                60: "60px",
                100: "100px",
                120: "120px",
                190: "190px",
            },
            padding: {
                0.25: "1px",
                3.5: "14px",
                7.5: "30px",
                c60: "60px",
                21: "21px",
                26: "26px",
                120: "120px",
            },
            ringWidth: {
                0.6: "0.6px",
            },
            spacing: {
                15: "15px",
            },
            width: {
                84: "84px",
                98: "98px",
                100: "100px",
                181: "181px",
                210: "210px",
                220: "220px",
                396: "396px",
                400: "400px",
                415: "415px",
                516: "516px",
                616: "616px",
                636: "636px",
                816: "816px",
                856: "856px",
            },
            keyframes: {
                opacityChange: {
                    "0%, 100%": { opacity: "1" },
                    "50%": { opacity: "0.5" },
                },
                opacityProduct: {
                    "0%": { opacity: "0" },
                    "100%": { opacity: "1" },
                },
            },
            animation: {
                opacityChange: "opacityChange 5s infinite",
                opacityProduct: "opacityProduct 0.3s ease-in-out",
            },
            boxShadow: {
                navbar: "0 4px 10px -3px rgba(191, 191, 191, 0.5)",
                abouthero: "0 2px 15px 0px rgba(0, 0, 0, 0.1)",
                activelinkproduct: "0px 0 25px rgba(0, 0, 0, 0.08)",
            },
        },
    },
    plugins: [],
};
